import os
print("Updating apps and system! 0/2")
os.system("sudo apt-get --yes update")
print("50% done of updates, 20% done all. 1/2")
os.system("sudo apt-get --yes upgrade")
print("100% done updates 2/2, 40% done")
print("Downloading The Software!")
os.system("sudo apt-get --yes install python3-dev python3-pip")
print("44% done of software 1/3, 60% done")
os.system("sudo pip3 install spidev")
print("83% done of software 2/3, 80% done")
os.system("sudo pip3 install mfrc522")
print("100% done of software 3/3, 100% done%")
print("all done")
